// Code generated by mockery v2.23.1. DO NOT EDIT.

package dispatcher

import (
	object "aegis/internal/object"

	mock "github.com/stretchr/testify/mock"
)

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

// ScanObject provides a mock function with given fields: _a0, _a1
func (_m *MockScanner) ScanObject(_a0 *object.Object, _a1 chan error) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewMockScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockScanner(t mockConstructorTestingTNewMockScanner) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
