logger:
  level: debug
  encoding: console
minio:
  endpoint: 10.10.6.233:9000
  access_key: minioadmin
  secret_key: minioadmin
  use_ssl: false
kafka:
  brokers:
    - 127.0.0.1:9092
  topic: test-topic
  group_id: g1
  max_bytes: 10
clamav:
  remove_after_scan: true
  datetime_format: "01-02-2006 15:04:05"
  path: cache/
prometheus:
  endpoint: 127.0.0.1:2112
  path: /metrics
postgres:
  user: postgres
  password: postgres
  host: 127.0.0.1:5432
  database: aegis_antivirus
  table: aegis_audit_logs
