apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: aegis
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "12345"
ports:
  # Expose MinIO
  - port: 9001:30001
    nodeFilters:
      - server:0
  # Expose Prometheus
  - port: 9090:30090
    nodeFilters:
      - server:0
  # Expose Postgresql
  - port: 5432:30080
    nodeFilters:
      - server:0
