// Code generated by mockery v2.23.1. DO NOT EDIT.

package events

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventsQueue is an autogenerated mock type for the EventsQueue type
type MockEventsQueue struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockEventsQueue) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadMessage provides a mock function with given fields: _a0
func (_m *MockEventsQueue) ReadMessage(_a0 context.Context) (string, string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMockEventsQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEventsQueue creates a new instance of MockEventsQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEventsQueue(t mockConstructorTestingTNewMockEventsQueue) *MockEventsQueue {
	mock := &MockEventsQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
