// Code generated by mockery v2.23.1. DO NOT EDIT.

package events

import mock "github.com/stretchr/testify/mock"

// MockEventsCollector is an autogenerated mock type for the EventsCollector type
type MockEventsCollector struct {
	mock.Mock
}

// MessageReceived provides a mock function with given fields:
func (_m *MockEventsCollector) MessageReceived() {
	_m.Called()
}

type mockConstructorTestingTNewMockEventsCollector interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEventsCollector creates a new instance of MockEventsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEventsCollector(t mockConstructorTestingTNewMockEventsCollector) *MockEventsCollector {
	mock := &MockEventsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
