// Code generated by mockery v2.23.1. DO NOT EDIT.

package cleaner

import mock "github.com/stretchr/testify/mock"

// MockCleanerCollector is an autogenerated mock type for the CleanerCollector type
type MockCleanerCollector struct {
	mock.Mock
}

// CleanupError provides a mock function with given fields:
func (_m *MockCleanerCollector) CleanupError() {
	_m.Called()
}

// ObjectQuarantined provides a mock function with given fields:
func (_m *MockCleanerCollector) ObjectQuarantined() {
	_m.Called()
}

// ObjectRemoved provides a mock function with given fields:
func (_m *MockCleanerCollector) ObjectRemoved() {
	_m.Called()
}

// ObjectTagged provides a mock function with given fields:
func (_m *MockCleanerCollector) ObjectTagged() {
	_m.Called()
}

type mockConstructorTestingTNewMockCleanerCollector interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCleanerCollector creates a new instance of MockCleanerCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCleanerCollector(t mockConstructorTestingTNewMockCleanerCollector) *MockCleanerCollector {
	mock := &MockCleanerCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
