// Code generated by mockery v2.23.1. DO NOT EDIT.

package scanner

import mock "github.com/stretchr/testify/mock"

// MockScanCollector is an autogenerated mock type for the ScanCollector type
type MockScanCollector struct {
	mock.Mock
}

// CleanFile provides a mock function with given fields:
func (_m *MockScanCollector) CleanFile() {
	_m.Called()
}

// FileScanned provides a mock function with given fields:
func (_m *MockScanCollector) FileScanned() {
	_m.Called()
}

// InfectedFile provides a mock function with given fields:
func (_m *MockScanCollector) InfectedFile() {
	_m.Called()
}

// ScanError provides a mock function with given fields:
func (_m *MockScanCollector) ScanError() {
	_m.Called()
}

// ScanTime provides a mock function with given fields: _a0
func (_m *MockScanCollector) ScanTime(_a0 float64) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewMockScanCollector interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockScanCollector creates a new instance of MockScanCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockScanCollector(t mockConstructorTestingTNewMockScanCollector) *MockScanCollector {
	mock := &MockScanCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
