// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// KafkaReader is an autogenerated mock type for the KafkaReader type
type KafkaReader struct {
	mock.Mock
}

// ReadMessage provides a mock function with given fields: _a0
func (_m *KafkaReader) ReadMessage(_a0 context.Context) (kafka.Message, error) {
	ret := _m.Called(_a0)

	var r0 kafka.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kafka.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kafka.Message); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kafka.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKafkaReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaReader creates a new instance of KafkaReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaReader(t mockConstructorTestingTNewKafkaReader) *KafkaReader {
	mock := &KafkaReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
