// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KafkaCollector is an autogenerated mock type for the KafkaCollector type
type KafkaCollector struct {
	mock.Mock
}

// MessageReceived provides a mock function with given fields:
func (_m *KafkaCollector) MessageReceived() {
	_m.Called()
}

type mockConstructorTestingTNewKafkaCollector interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaCollector creates a new instance of KafkaCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaCollector(t mockConstructorTestingTNewKafkaCollector) *KafkaCollector {
	mock := &KafkaCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
