// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ObjectStore is an autogenerated mock type for the ObjectStore type
type ObjectStore struct {
	mock.Mock
}

// AddObjectTagging provides a mock function with given fields: _a0, _a1, _a2
func (_m *ObjectStore) AddObjectTagging(_a0 string, _a1 string, _a2 map[string]string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetObject provides a mock function with given fields: _a0, _a1
func (_m *ObjectStore) GetObject(_a0 string, _a1 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewObjectStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewObjectStore creates a new instance of ObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewObjectStore(t mockConstructorTestingTNewObjectStore) *ObjectStore {
	mock := &ObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
