// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	object "aegis/internal/object"

	mock "github.com/stretchr/testify/mock"
)

// Scanner is an autogenerated mock type for the Scanner type
type Scanner struct {
	mock.Mock
}

// ScanObject provides a mock function with given fields: _a0
func (_m *Scanner) ScanObject(_a0 *object.Object) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*object.Object) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewScanner creates a new instance of Scanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScanner(t mockConstructorTestingTNewScanner) *Scanner {
	mock := &Scanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
