apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.env.MINIO_ENDPOINT }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.auth.rootUser }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.auth.rootPasword }}
            - name: KAFKA_BROKERS
              value: {{ .Values.env.KAFKA_BROKERS }}
            - name: KAFKA_TOPIC
              value: {{ (first .Values.kafka.provisioning.topics)}}
            - name: PROMETHEUS_ENDPOINT
              value: {{ .Values.env.PROMETHEUS_ENDPOINT }}
            - name: PROMETHEUS_PATH
              value: {{ .Values.env.PROMETHEUS_PATH }}
            - name: POSTGRESQL_ENDPOINT
              value: {{ .Values.env.POSTGRESQL_ENDPOINT }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresqlql.auth.database }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
