apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  ports:
    - name: minio
      nodePort: 30001
      port: 9001
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio
  type: NodePort
