apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
    - name: prometheus
      nodePort: 30090
      port: 9090
      protocol: TCP
  selector:
    app: prometheus
    component: server
  type: NodePort
