apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  ports:
    - name: postgresql
      nodePort: 30080
      port: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
  type: NodePort
