// Code generated by mockery v2.23.1. DO NOT EDIT.

package metrics

import mock "github.com/stretchr/testify/mock"

// MockMetricService is an autogenerated mock type for the MetricService type
type MockMetricService struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockMetricService) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockMetricService) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockMetricService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetricService creates a new instance of MockMetricService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetricService(t mockConstructorTestingTNewMockMetricService) *MockMetricService {
	mock := &MockMetricService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
